name: flutter_korea_paylauncher
description: Flutter library for launching Korean payment apps and handling payment app redirects.
version: 0.0.1+1
homepage: https://github.com/chul0061/flutter_korea_paylauncher
repository: https://github.com/chul0061/flutter_korea_paylauncher
issue_tracker: https://github.com/chul0061/flutter_korea_paylauncher/issues

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
